trigger: 
- main
pool:
    name: SelfAgent
variables:
    buildConfiguration: 'Release'
steps:
- bash: echo hello world
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'